### ISSUE TITLE
Downloading data request a Baidu account which cannot accessible to foreigners

### ISSUE THREAD

**Issue by DaebangStn** [boycehbz/HumanInteraction#1]
Thank you for releasing great works. I am delighted to check your codes on online. 

Unfortunately, to download annotation or checkpoint, Baidu account is required which is that affordable for people live outside China.
Since the file is hosted on the baidu, they request me to login to baidu. But I cannot make a baidu account because I don't have phone number inside China.

Could you please upload data on the other points, (like google drives or onedrives...)
Thank you!

**Comment by boycehbz** [comment]
Hi, thanks for your interest! I have provided a link on Google Drive. You can check the latest README file.

**Comment by DaebangStn** [comment]
Thank you for your kind reply. GOOD LUCK!
